package index

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestIsGenerated(t *testing.T) {
	cases := []struct {
		src  string
		want bool
	}{
		{"// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage x\n", true},
		{"// Code generated by \"stringer\"; DO NOT EDIT.\npackage x\n", true},
		{"# Code generated by protoc. DO NOT EDIT.\n", true},                       // Python
		{"//go:build linux\n\n// Code generated by mockgen. DO NOT EDIT.\n", true}, // after a build tag
		{"package x\n\nfunc Foo() {}\n", false},
		{"// A normal doc comment about generated data.\npackage x\n", false}, // must match the marker
		{"// this file was generated but not with the marker\n", false},
	}

	for _, c := range cases {
		assert.Equal(t, c.want, isGenerated([]byte(c.src)), "src: %q", c.src)
	}
}

func TestMatchExclude(t *testing.T) {
	cases := []struct {
		pattern, path string
		want          bool
	}{
		{"*.pb.go", "v2/pkg/x/product.pb.go", true}, // bare basename glob, any dir
		{"**/*.pb.go", "a/b/c.pb.go", true},         // explicit any-dir
		{"*_test.go", "pkg/foo_test.go", true},      // tests
		{"*_test.go", "pkg/foo.go", false},
		{"vendor/", "vendor/x/y.go", true}, // dir prefix
		{"vendor/", "internal/vendorish.go", false},
		{"internal/gen/", "internal/gen/api.go", true},
		{"api/schemas.py", "api/schemas.py", true}, // exact
		{"api/schemas.py", "other/schemas.py", false},
	}

	for _, c := range cases {
		assert.Equal(t, c.want, matchExclude(c.pattern, c.path),
			"pattern %q vs %q", c.pattern, c.path)
	}
}

func TestLoadConfigDefaultsAndParse(t *testing.T) {
	// Absent file → defaults (index generated=false, no excludes).
	cfg, err := LoadConfig(t.TempDir())
	require.NoError(t, err)
	assert.False(t, cfg.Index.Generated)
	assert.Empty(t, cfg.Index.Exclude)

	root := t.TempDir()
	require.NoError(t, os.MkdirAll(filepath.Join(root, ".seamark"), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(root, ".seamark", "config.yaml"),
		[]byte("index:\n  generated: true\n  exclude:\n    - '**/*.pb.go'\n"), 0o644))

	cfg, err = LoadConfig(root)
	require.NoError(t, err)
	assert.True(t, cfg.Index.Generated)
	require.Len(t, cfg.Index.Exclude, 1)
	assert.True(t, cfg.excluded("a/b.pb.go"))
	assert.False(t, cfg.excluded("a/b.go"))
}

func TestCheckExclude(t *testing.T) {
	for _, ok := range []string{
		"*.pb.go", "**/*_test.go", "internal/gen/", "api/schemas.py", "./x.go",
	} {
		assert.NoError(t, checkExclude(ok), "pattern %q", ok)
	}

	for _, bad := range []string{
		"",            // matches nothing
		"[",           // glob syntax error
		"**/gen/*.go", // `**/` takes a basename, not a path
		"a/**/b.go",   // mid-path ** never matches (path.Match is per-segment)
		"a**.go",      // ditto — reject rather than quietly act like a*.go
	} {
		assert.Error(t, checkExclude(bad), "pattern %q", bad)
	}
}

func TestLoadConfigRejectsBadExclude(t *testing.T) {
	// A never-matching exclude must fail the load with the pattern named,
	// not be silently ignored — same contract as malformed YAML.
	root := t.TempDir()
	require.NoError(t, os.MkdirAll(filepath.Join(root, ".seamark"), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(root, ".seamark", "config.yaml"),
		[]byte("index:\n  exclude:\n    - 'internal/**/*.pb.go'\n"), 0o644))

	_, err := LoadConfig(root)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "internal/**/*.pb.go")
}

func TestLoadConfigRejectsMalformed(t *testing.T) {
	root := t.TempDir()
	require.NoError(t, os.MkdirAll(filepath.Join(root, ".seamark"), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(root, ".seamark", "config.yaml"),
		[]byte("index: [not a map\n"), 0o644))

	_, err := LoadConfig(root)
	require.Error(t, err)
}
